### PR TITLE
change colors of the button

### PR DESCRIPTION
**Pull request by Ezzeldien-M-Abdalaziz**

### CODE REVIEW

**Comment by Mano4life** [comment]
is this only for the button ? did you also apply for the texts and highlights ?

**Comment by Ezzeldien-M-Abdalaziz** [comment]
yes !

**Comment by Mano4life** [comment]
I see! kindly apply the theme to all your texts and highlights :smile:

**Review by Mano4life — APPROVED** [review]
great work! thank you.

**Pull request merged**
